# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastAIcourse',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/fastAIcourse',
                'lib_path': 'fastAIcourse'},
  'syms': {'fastAIcourse.core': {'fastAIcourse.core.foo': ('core.html#foo', 'fastAIcourse/core.py')}}}
