# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/170_convolutions.ipynb.

# %% auto 0
__all__ = ['def_device', 'apply_kernel', 'conv', 'to_device', 'collate_device']

# %% ../nbs/170_convolutions.ipynb 3
import torch
from torch import nn

from torch.utils.data import default_collate
from typing import Mapping

from .training import *
from .datasets import *

# %% ../nbs/170_convolutions.ipynb 27
def apply_kernel(row, col, kernel): return (im3[row-1:row+2,col-1:col+2] * kernel).sum()

# %% ../nbs/170_convolutions.ipynb 37
import torch.nn.functional as F
import torch

# %% ../nbs/170_convolutions.ipynb 58
from itertools import zip_longest

# %% ../nbs/170_convolutions.ipynb 72
def conv(ni, nf, ks=3, stride=2, act=True):
    res = nn.Conv2d(ni, nf, stride=stride, kernel_size=ks, padding=ks//2)
    if act: res = nn.Sequential(res, nn.ReLU())
    return res

# %% ../nbs/170_convolutions.ipynb 79
def_device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'
def_device

# %% ../nbs/170_convolutions.ipynb 80
def to_device(x, device=def_device):
    if isinstance(x, torch.Tensor): return x.to(device)
    if isinstance(x, Mapping): return {k:v.to(device) for k,v in x.items()}
    return type(x)(to_device(o, device) for o in x)

def collate_device(b): return to_device(default_collate(b))
