# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_NeuralNet.ipynb.

# %% auto 0
__all__ = ['read_from_file']

# %% ../nbs/02_NeuralNet.ipynb 13
#|code-fold: true
def read_from_file(file_path):
    countries = ()
    with open(file_path, 'r') as file:
        for line in file:
            # Remove any leading/trailing whitespace and newline characters
            country = line.strip()
            # Add the country to the tuple
            countries += (country,)

    return countries
