# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/140_minibatch_training.ipynb.

# %% auto 0
__all__ = ['Model']

# %% ../nbs/140_minibatch_training.ipynb 7
class Model(nn.Module):
    def __init__(self, n_in, nh, n_out):
        super().__init__()
        self.layers = [nn.Linear(n_in,nh), nn.ReLU(), nn.Linear(nh,n_out)]
        
    def __call__(self, x):
        for l in self.layers: x = l(x)
        return x
